name: jolly_podcast
description: A professional Flutter podcast application for Bloocode Technology assessment
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
    - family: FuturaPT
      fonts:
        - asset: assets/fonts/FuturaCyrillicBook.ttf
          weight: 400
        - asset: assets/fonts/FuturaCyrillicHeavy.ttf
          weight: 600
